pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    # プルリクエストが特定のルールに一致しているか
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build-test
    # プルリクエストがルールに一致している場合に実行されるアクション
    actions:
      # ベースのブランチにプルリクエストをマージ
      merge:
        method: merge
  - name: automatic update for PR“
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$o
        #commits-behind!=0
    actions:
      update:
