pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author = dependabot[bot]
      - '#approved-reviews-by >= 1'
      - check-success = build-test
      - check-success = check-lint-and-format
    actions:
      merge:
        method: merge
  - name: automatic update for PR“
    conditions:
      - author = dependabot[bot]
      - '#commits-behind != 0'
    actions:
      update:
