name: Generate token by GitHub Apps

on:
  push:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Commands
        run: ls -l

      - name: Generate GitHub Apps token
        id: generate
        env:
          APP_ID: ${{ secrets.APP_ID }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          chmod u+x ./script.sh
          ./script.sh

      - name: Checkout private repos
        uses: actions/checkout@v3
        with:
          repository: idaten-hack/team-generator-logic
          token: ${{ steps.generate.outputs.token }}

      - name: Commands
        run: ls -l
