name: Generate token by GitHub Apps

on:
  push:

jobs:
  generate-token:
    name: Generate
    uses: idaten-hack/actions/.github/workflows/generate-token.yml@main
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

  checkout:
    runs-on: ubuntu-latest
    needs: generate-token
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Checkout private repos
        uses: actions/checkout@v3
        with:
          repository: idaten-hack/team-generator-logic
          token: ${{ needs.generate-token.outputs.token }}
          paths: logic

      - name: Commands
        run: ls -l

